name: unit-tests
run-name: ${{ github.head_ref || github.ref_name }}-unit-tests

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: 'ubuntu-22.04'
      godot-version:
        required: true
        type: string
      godot-status:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      os:
        required: false
        type: string
        default: 'ubuntu-22.04'
      godot-version:
        required: true
        type: string
      godot-status:
        required: true
        type: string

concurrency:
  group: unit-tests-${{ github.head_ref || github.ref_name }}-${{ inputs.godot-version }}
  cancel-in-progress: true

jobs:

  unit-test-runner:
    name: "Unit Tests With TestRunner"
    runs-on: ${{ inputs.os }}
    timeout-minutes: 5

    steps:
      - name: "Checkout GdUnit Repository"
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: "Install Godot Mono ${{ inputs.godot-version }}"
        uses: ./.github/actions/godot-install
        with:
          godot-version: ${{ inputs.godot-version }}
          godot-mono: true
          godot-status-version: ${{ inputs.godot-status }}
          godot-bin-name: 'linux_x86_64'
          godot-cache-path: '~/godot-linux'

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Compile C#"
        if: ${{ !cancelled() }}
        run: |
          dotnet restore ./api/gdUnit4Api.csproj
          dotnet build ./api/gdUnit4Api.csproj
          dotnet restore ./testadapter/gdUnit4TestAdapter.csproj
          dotnet build ./testadapter/gdUnit4TestAdapter.csproj
          dotnet restore ./test/gdUnit4Test.csproj
          dotnet build ./test/gdUnit4Test.csproj

      - name: "Run Unit Tests"
        if: ${{ !cancelled() }}
        timeout-minutes: 5
        uses: ./.github/actions/unit-test
        with:
          godot-bin: '~/godot-linux/godot'
          test-includes: "res://test/src"

#      - name: "Set Report Name"
#        if: ${{ always() }}
#        shell: bash
#        run: echo "REPORT_NAME=${{ inputs.os }}-${{ inputs.godot-version }}-mono" >> "$GITHUB_ENV"

#      - name: "Publish Unit Test Reports"
#        if: ${{ !cancelled() }}
#        uses: ./.github/actions/publish-test-report
#        with:
#          report-name: ${{ env.REPORT_NAME }}

#      - name: "Upload Unit Test Reports"
#        if: ${{ !cancelled() }}
#        uses: ./.github/actions/upload-test-report
#        with:
#          report-name: ${{ env.REPORT_NAME }}

  unit-test-adapter:
    name: "Unit Tests With TestAdapter"
    runs-on: ${{ inputs.os }}
    timeout-minutes: 5

    steps:
      - name: "Checkout GdUnit Repository"
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: "Install Godot Mono ${{ inputs.godot-version }}"
        uses: ./.github/actions/godot-install
        with:
          godot-version: ${{ inputs.godot-version }}
          godot-mono: true
          godot-status-version: ${{ inputs.godot-status }}
          godot-bin-name: 'linux_x86_64'
          godot-cache-path: '~/godot-linux'

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Compile C#"
        if: ${{ !cancelled() }}
        run: |
          dotnet restore ./api/gdUnit4Api.csproj
          dotnet build ./api/gdUnit4Api.csproj
          dotnet restore ./testadapter/gdUnit4TestAdapter.csproj
          dotnet build ./testadapter/gdUnit4TestAdapter.csproj
          dotnet restore ./test/gdUnit4Test.csproj
          dotnet build ./test/gdUnit4Test.csproj

      - name: "Run Unit Tests"
        if: ${{ !cancelled() }}
        timeout-minutes: 5
        env:
          GODOT_BIN: "/home/runner/godot-linux/godot"
        run: |
          $GODOT_BIN --path ./test -e --quit --headless
          xvfb-run --auto-servernum dotnet test ./test/gdUnit4Test.csproj --no-build --settings ./test/.runsettings-ci

      - name: "Set Report Name"
        if: ${{ always() }}
        shell: bash
        run: echo "REPORT_NAME=${{ inputs.os }}-${{ inputs.godot-version }}" >> "$GITHUB_ENV"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ env.REPORT_NAME }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ env.REPORT_NAME }}